### ISSUE TITLE
Predict Probabilities

### ISSUE THREAD

**Issue by slal73** [ThilinaRajapakse/simpletransformers#332] opened 2020-04-28 19:01 UTC
how to predict probabilities in multiclass classification?

**Comment by ThilinaRajapakse** [comment] 2020-04-28 19:21
Duplicate of #30 

See comment [here](https://github.com/ThilinaRajapakse/simpletransformers/issues/30#issuecomment-550438980).

**Closed by ThilinaRajapakse** 2020-04-28 19:21 UTC
