### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.models.mmbt'

### ISSUE THREAD

**Issue by DeepakGaurAerospace** [ThilinaRajapakse/simpletransformers#1539] opened 2023-07-20 05:56 UTC
For BERT model training in Colab, I have installed following libraries:

1. !pip install simpletransformers
2. !pip install transformers -U (4.31.0)
3. !pip install --upgrade tqdm (4.65.0)
4. !pip install --upgrade simpletransformers

**To Reproduce**

import simpletransformers
from simpletransformers.classification import ClassificationModel

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-23-e269f817f0ec>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from simpletransformers.classification import ClassificationModel

1 frames
[/usr/local/lib/python3.10/dist-packages/simpletransformers/classification/multi_modal_classification_model.py](https://localhost:8080/#) in <module>
     45     BertTokenizer,
     46 )
---> 47 from transformers.models.mmbt.configuration_mmbt import MMBTConfig
     48 
     49 from simpletransformers.classification.classification_utils import (

**ModuleNotFoundError: No module named 'transformers.models.mmbt'**

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Expected behavior**
Previously, when I tried calling this function, it worked flawlessly, which was barely 3 days earlier. 

**Screenshots**
![image](https://github.com/ThilinaRajapakse/simpletransformers/assets/49327238/9ac08cd7-fbb8-480d-b733-fa4dc523ea85)

**Comment by ctestagrose** [comment] 2023-07-20 13:02
I am also having this same problem with similar steps to reproduce.

```
!pip install simpletransformers
from simpletransformers.classification import ClassificationModel, ClassificationArgs, MultiLabelClassificationModel, MultiLabelClassificationArgs
```

This results in:
```
ModuleNotFoundError: No module named 'transformers.models.mmbt'
```

I am also using Colab.

**Comment by PeeratPookpanich** [comment] 2023-07-20 13:15
![image](https://github.com/ThilinaRajapakse/simpletransformers/assets/68580377/c450917a-594c-4d70-ac60-4a2f6087dbaa)

I had the same issue.

**Comment by owendw1** [comment] 2023-07-20 13:20
Until this is fixed, the following workaround can be used (see issue #1538):

!pip install simpletransformers "transformers==4.30.2"

**Comment by PeeratPookpanich** [comment] 2023-07-20 13:46
> Until this is fixed, the following workaround can be used (see issue #1538):
> 
> !pip install simpletransformers "transformers==4.30.2"

This is work for me. Thanks !

**Comment by tugrulz** [comment] 2023-07-20 15:46
Same here.

**Comment by willkats** [comment] 2023-07-21 09:25
This workaround worked for me. However, when trying to infer/predict using a pre-trained classification model I get this error referring back to the ClassificationModel.predict() function. Anybody knows what's up here?

<img width="1232" alt="Screenshot 2023-07-21 at 3 09 42 PM" src="https://github.com/ThilinaRajapakse/simpletransformers/assets/113324067/b1c19b04-44fc-4ead-adbe-0f318b8307ed">

**Comment by willkats** [comment] 2023-07-21 09:26
This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!

![Uploading Screenshot 2023-07-21 at 3.08.05 PM.png…]()

**Comment by willkats** [comment] 2023-07-21 09:27
This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!

<img width="981" alt="Screenshot 2023-07-21 at 3 08 05 PM" src="https://github.com/ThilinaRajapakse/simpletransformers/assets/113324067/6b6b48e1-e9db-401b-aa1b-d487c4749be5">

**Comment by willkats** [comment] 2023-07-21 09:29
This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!

<img width="1173" alt="Screenshot 2023-07-21 at 3 10 29 PM" src="https://github.com/ThilinaRajapakse/simpletransformers/assets/113324067/279b4c8c-b88e-47b7-8fc8-f73ba2c1262c">

**Comment by owendw1** [comment] 2023-07-21 11:50
> 



> This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!



> This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!
> <img alt="Screenshot 2023-07-21 at 3 10 29 PM" width="1173" src="https://user-images.githubusercontent.com/113324067/255135111-279b4c8c-b88e-47b7-8fc8-f73ba2c1262c.png">

The predict method works in the examples I've just tried. Could you share your code with us? Maybe we can work out what's happening.

**Comment by willkats** [comment] 2023-07-21 14:12
Thank you 

> > This workaround worked for me. However, when trying to infer/predict using a pre-trained model, i get this error. Anybody knows what's going on here? I dire need. Thanks!
> > <img alt="Screenshot 2023-07-21 at 3 10 29 PM" width="1173" src="https://user-images.githubusercontent.com/113324067/255135111-279b4c8c-b88e-47b7-8fc8-f73ba2c1262c.png">
> 
> The predict method works in the examples I've just tried. Could you share your code with us? Maybe we can work out what's happening.

Thank you so much. This is the whole code. Pretty simple, I'm loading a pre-trained model to predict. It pretty much runs through but fails at the very end. Any help would be much appreciated! 
<img width="1154" alt="Screenshot 2023-07-21 at 7 56 11 PM" src="https://github.com/ThilinaRajapakse/simpletransformers/assets/113324067/92e8d545-6565-4029-850a-e4729f3afcdf">

**Comment by owendw1** [comment] 2023-07-22 00:27
> This is the whole code. Pretty simple, I'm loading a pre-trained model to predict. It pretty much runs through but fails at the very end. Any help would be much appreciated!

I can't seem to recreate the error, despite trying saving and loading a number of roberta based models. It's possible that there's something about the particular model being loaded that simple transformers or scipy isn't getting on with.

I notice that in the latest version of scipy (1.11.1) the default behaviour of the mode method has changed. Assuming the latest version of scipy was installed as a dependency when simple transformers was installed, maybe using a previous version of scipy could help. Perhaps try the following:

pip install simpletransformers "transformers==4.30.2" "scipy==1.10.1"

This is only a slight possibility though unfortunately. I think it's difficult to say for sure what the problem is without looking at your conda environment and saved model in detail.

**Comment by willkats** [comment] 2023-07-22 11:03
> > This is the whole code. Pretty simple, I'm loading a pre-trained model to predict. It pretty much runs through but fails at the very end. Any help would be much appreciated!
> 
> I can't seem to recreate the error, despite saving and loading a number of roberta based models. It's possible that there's something about the particular model being loaded that simple transformers or scipy isn't getting on with.
> 
> I notice that in the latest version of scipy (1.11.1) the default behaviour of the mode method has changed. Assuming the latest version of scipy was installed as a dependency when simple transformers was installed, maybe instead using a previous version of scipy could help. Perhaps try the following:
> 
> pip install simpletransformers "transformers==4.30.2" "scipy==1.10.1"
> 
> This is only a slight possibility though unfortunately. I think it's difficult to say for sure what the problem is without taking a look at your conda environment and saved model in detail.

Installing simpletransformers with scipy1.10.1 indeed worked! Seemed like incompatibility with new scipy mode function was the issue. Thank you so much!

**Comment by ThilinaRajapakse** [comment] 2023-07-23 05:49
Looks like the latest version of transformers is incompatible with the current Simple Transformers version. I will look into this next week. Until then, please use the workaround suggested by @owendw1 (thanks!).

**Comment by ThilinaRajapakse** [comment] 2023-08-03 15:47
This should be fixed now. The latest version of Simple Transformers should be compatible with the latest Transformers (as well as Python and PyTorch) versions.

**Closed by ThilinaRajapakse** 2023-08-03 15:47 UTC
