### ISSUE TITLE
ValueError: too many dimensions 'str' for multiclass - sentence pair classification

### ISSUE THREAD

**Issue by akeserel** [ThilinaRajapakse/simpletransformers#123] opened 2020-01-04 22:11 UTC
Hello,

I am trying to replicate the steps in this article:

https://medium.com/@vslovik/fake-news-detection-empowered-with-bert-and-friends-20397f7e1675
This is how I implement the model:
model = ClassificationModel('roberta', 'roberta-base', num_labels=4, use_cuda=False, args={'reprocess_input_data': True, 'overwrite_output_dir': True})
model.train_model(train_df)

I get this error:
xamples(self, examples, evaluate, no_cache, multi_label)
    511 
    512         if output_mode == "classification":
--> 513             all_label_ids = torch.tensor([f.label_id for f in features], dtype=torch.long)
    514         elif output_mode == "regression":
    515             all_label_ids = torch.tensor([f.label_id for f in features], dtype=torch.float)

ValueError: too many dimensions 'str'

My data frame has text_a, text_b and label headings. When I try to drop one column (text_a or text_b) it works, so there is a problem with sentence pairs I guess. Can you help me with this?
![d_frame](https://user-images.githubusercontent.com/2893132/71772204-3de0ed80-2f58-11ea-8d44-0b58be946faf.png)

**Comment by ThilinaRajapakse** [comment] 2020-01-05 13:37
Sentence pair tasks are not supported atm. I've been meaning to look into it, but haven't found the time yet.

**Comment by ThilinaRajapakse** [comment] 2020-01-05 13:38
Duplicate of #111

**Closed by ThilinaRajapakse** 2020-01-05 13:38 UTC

**Comment by Sphinxs** [comment] 2020-12-15 00:56
Any updates?

**Comment by ThilinaRajapakse** [comment] 2020-12-21 17:12
This has been supported for a long time now.

**Comment by Sphinxs** [comment] 2020-12-21 20:08
Strange, I received this error while trying to input 2 sequences associated with my N classes codified as 0 and 1. Here's a list of my dependencies:

```
pandas===1.1.4
numpy===1.19.4
scikit-learn===0.23.2
torch===1.7.1
onnx===1.8.0
transformers===4.0.1
simpletransformers===0.51.3
wandb===0.10.12
```

Reading the data section of Simple Transformers I saw that two input sentences are actually similarity analysis task, right?
