### ISSUE TITLE
multilabel classification metrics issue

### ISSUE THREAD

**Issue by rajae-Bens** [ThilinaRajapakse/simpletransformers#785] opened 2020-10-25 07:22 UTC
Hi,

I ve applied the multilabel classification model to my own dataset, but when I tried to calculate the sklearn.metrics such as f1 score and precision score, I got this error 

ValueError: Classification metrics can't handle a mix of unknown and multilabel-indicator targets

the format of my column labels is 

![Screen Shot 2020-10-25 at 8 19 53 AM](https://user-images.githubusercontent.com/58187895/97101131-eeacaa80-169a-11eb-9e69-00c6045fd6f2.png)

and for the predictions: 

I got this format  using  model_outputs.round().astype('int')

[[0 1 1 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 ...
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 0 1 0]
 [0 1 1 ... 1 0 0]]

could someone help me with this plz 

Thank u

**Comment by ThilinaRajapakse** [comment] 2020-10-31 15:16
Duplicate of #125

**Closed** 2020-10-31 22:04 UTC
Labels: duplicate
