### ISSUE TITLE
Additional metrics for evaluation in MultiLabelClassificationModel

### ISSUE THREAD

**Issue by Adel-Memariani** [ThilinaRajapakse/simpletransformers#916] opened 2020-12-26 07:44 UTC
I used the f1_score from sklearn.metrics as an additional metrics (a parameter for the train_model).

Here is my code:

```
from simpletransformers.classification import MultiLabelClassificationModel, MultiLabelClassificationArgs
from sklearn.metrics import f1_score

MODEL_ARGs = MultiLabelClassificationArgs(
    reprocess_input_data=True,
    overwrite_output_dir=True,
    num_train_epochs=1,
    train_batch_size=16,
    evaluate_during_training=True,
    evaluate_during_training_verbose=True,
    )

model = MultiLabelClassificationModel('roberta', 'path_to_my_pretrained_model',
                                              num_labels=NUM_LABELS,
                                              use_cuda=USE_CUDA,
                                              args=MODEL_ARGs,
                                      )

                                              
model.train_model(train_df=train_data, eval_df=validation_data, output_dir='path_to_model_output', f1=f1_score)

```

 However I got the following error:

```
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     88     if len(y_type) > 1:
     89         raise ValueError("Classification metrics can't handle a mix of {0} "
---> 90                          "and {1} targets".format(type_true, type_pred))
     91 
     92     # We can't have more than one value on y_type => The set is no more needed

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets
```

and couldn't find a solution. Any idea?

**Comment by ThilinaRajapakse** [comment] 2020-12-29 09:55
Duplicate of #125

**Closed by ThilinaRajapakse** 2020-12-29 09:55 UTC
