### ISSUE TITLE
Running it on Google Colab gives the following error : ValueError: Number of processes must be at least 1

### ISSUE THREAD

**Issue by SatyamSinghET** [ThilinaRajapakse/simpletransformers#2] opened 2019-10-07 05:23 UTC
Thanks for this library. I'm trying to run it on Google Colab and I'm getting the following error:
ValueError: Number of processes must be at least 1. I think its because of the process_count argument in convert_examples_to_features. 
```
def convert_examples_to_features(examples, max_seq_length,
                                 tokenizer, output_mode,
                                 cls_token_at_end=False, sep_token_extra=False, pad_on_left=False,
                                 cls_token='[CLS]', sep_token='[SEP]', pad_token=0,
                                 sequence_a_segment_id=0, sequence_b_segment_id=1,
                                 cls_token_segment_id=1, pad_token_segment_id=0,
                                 mask_padding_with_zero=True,
                                 process_count=cpu_count() - 2):
```

---------------------------------------------------------------------------
The entire stack trace is:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-d34e3006ce63> in <module>()
----> 1 model.train_model(train_split)

4 frames
/usr/local/lib/python3.6/dist-packages/simpletransformers/model.py in train_model(self, train_df, output_dir)
    125         train_examples = [InputExample(i, text, None, label) for i, (text, label) in enumerate(zip(train_df.iloc[:, 0], train_df.iloc[:, 1]))]
    126 
--> 127         train_dataset = self.load_and_cache_examples(train_examples)
    128         global_step, tr_loss = self.train(train_dataset, output_dir)
    129 

/usr/local/lib/python3.6/dist-packages/simpletransformers/model.py in load_and_cache_examples(self, examples, evaluate)
    272                                                     pad_token=tokenizer.convert_tokens_to_ids(
    273                 [tokenizer.pad_token])[0],
--> 274                 pad_token_segment_id=4 if args['model_type'] in ['xlnet'] else 0)
    275 
    276             torch.save(features, cached_features_file)

/usr/local/lib/python3.6/dist-packages/simpletransformers/utils.py in convert_examples_to_features(examples, max_seq_length, tokenizer, output_mode, cls_token_at_end, sep_token_extra, pad_on_left, cls_token, sep_token, pad_token, sequence_a_segment_id, sequence_b_segment_id, cls_token_segment_id, pad_token_segment_id, mask_padding_with_zero, process_count)
    170     examples = [(example, max_seq_length, tokenizer, output_mode, cls_token_at_end, cls_token, sep_token, cls_token_segment_id, pad_on_left, pad_token_segment_id, sep_token_extra) for example in examples]
    171 
--> 172     with Pool(process_count) as p:
    173         features = list(tqdm(p.imap(convert_example_to_feature, examples, chunksize=500), total=len(examples)))
    174 

/usr/lib/python3.6/multiprocessing/context.py in Pool(self, processes, initializer, initargs, maxtasksperchild)
    117         from .pool import Pool
    118         return Pool(processes, initializer, initargs, maxtasksperchild,
--> 119                     context=self.get_context())
    120 
    121     def RawValue(self, typecode_or_type, *args):

/usr/lib/python3.6/multiprocessing/pool.py in __init__(self, processes, initializer, initargs, maxtasksperchild, context)
    165             processes = os.cpu_count() or 1
    166         if processes < 1:
--> 167             raise ValueError("Number of processes must be at least 1")
    168 
    169         if initializer is not None and not callable(initializer):

ValueError: Number of processes must be at least 1

**Comment by ThilinaRajapakse** [comment] 2019-10-07 06:18
I forgot about this issue on Colab. The problem is the code is set to use cpu_count - 2 for processing. Unfortunately, Colab only has 2 CPUs. I'll push a fix to this in a few hours. Until then, you can clone the repo and change the process count argument to 1 or 2.

**Comment by samarthsarin** [comment] 2019-10-07 08:28
Yes, facing the same issue in kaggle kernels also. Please comment when you are done with updating the code. Thank you

**Comment by ThilinaRajapakse** [comment] 2019-10-07 13:58
Should be fixed now.

**Closed** 2019-10-09 06:00 UTC
